language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: 
    secure: PROCESS.ENV.ACCESS_KEY
  secret_access_key: 
    secure: PROCESS.ENV.SECRET_KEY
  bucket: "agency-fe"
  skip_cleanup: true
  acl: public_read 