language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: 
    secure: "AKIAJRUWGUOUA5QP3HRQ"
  secret_access_key: 
    secure: "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"
  bucket: "agency-fe"
  skip_cleanup: true
  region: eu-west-1g