language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: s3
  access_key_id: $access_key_id
  secret_access_key: $secret_access_key
  bucket: "agency-fe"
  skip_cleanup: true
  region: eu-west-1g